import type { FrameworkDef, PackContext } from './types'

const fmtSeconds = (ms: number) => `${(ms / 1000).toFixed(2).replace(/\.?0+$/, '')} s`

/** Renders the pack README: facts, files, quick start (headline lane), the
 *  alternative lane, fonts (when relevant), and the parity/controls notes. */
export function renderReadme(def: FrameworkDef, ctx: PackContext): string {
  const { meta } = ctx
  const date = new Date().toISOString().slice(0, 10)

  const fontFiles = ctx.fonts.map((f) => `- \`fonts/${f.file}\``).join('\n')
  const fontsSection = !meta.hasNativeText
    ? ''
    : ctx.fonts.length > 0
      ? `
## Fonts

This scene uses native Lottie text; its fonts ship in the pack:

${fontFiles}

Register each font with your player before loading the animation (font/asset
provider APIs vary per player) — the family name inside \`animation.json\`
(\`fonts.list[].fFamily\`) must match the font file's embedded family name.
`
      : `
## Fonts

> **Warning:** this scene uses native Lottie text, but the pack could not
> include its font files (the engine that produced it predates the fonts
> pipeline). Text may render in a fallback font on device. Re-export after
> the fonts update, or ask the design team for a vector-text variant.
`

  return `# ZENimator animation — ${def.label} pack

Authored by the ZENimator studio engine and verified frame-by-frame on Skia
(Skottie). Control values were baked in at export time.

| size | fps | frames | duration | loop |
|---|---|---|---|---|
| ${meta.w}×${meta.h} | ${meta.fps} | ${meta.frames} | ${fmtSeconds(meta.durationMs)} | ${ctx.loop ? 'yes' : 'no'} |

## Files

- \`animation.lottie\` — dotLottie package (for the dotlottie players)
- \`animation.json\` — plain Lottie (for lottie-web / airbnb players)
- \`${def.componentPath}\` — paste-ready component, wired for this animation
- \`README.md\` — this file
${ctx.fonts.length > 0 ? ctx.fonts.map((f) => `- \`fonts/${f.file}\` — required by the scene's native text`).join('\n') + '\n' : ''}
## Quick start

${def.quickStart(ctx)}

## Alternative: ${def.alternativeLabel}

${def.alternative(ctx)}
${fontsSection}
## Rendering parity

The animation was authored and verified on Skia. All dotlottie runtimes (web,
iOS, Android, React Native, Flutter) share the ThorVG engine, so they render
alike across platforms. If a frame looks off in your player, try the
plain-JSON lane — and report it back to the design team so the scene can be
adjusted.

## Changing it

Slider values are baked into these files. To tweak motion, timing, or
intensity, re-export from ZENimator — don't hand-edit the JSON.

---
Generated by ZENimator · ${date}
`
}
